### ISSUE TITLE
How to use context variables in redux actions.

### ISSUE THREAD

**Issue by tomitrescak** [saschb2b/meteor-mantra-react-redux-kickstarter#1]
Very nice project! I am working on something similar and this is really helpful. I have a question concerning the redux actions. Since you have redux store as part of your context, redux actions will not have access to context variables. For example if in the action I will decide to use Flow router to move to different URL, you would have no access to it. As a result I made context part of the redux state but have very bad feeling about it. How would you solve this problem? Any help is very welcome!

The only way I think it is doable is to pass those variables from container's context as parameters.

**Comment by saschb2b** [comment]
Good question. Injectiing context (here FlowRouter) into components can be seen here https://github.com/saschb2b/meteor-mantra-react-redux-kickstarter/commit/827f6700afd19e58f847f5e99a1ac99970792f43

But using it internally for actions is something I haven't done before. Let me fiddle a bit :)
I'll try to inject it into the reducer so that you can dispatch an action to change route with flow router.
Not sure if this would be good approche yet.

But making context part of the redux state seems very redundant to me. There should be a better solution. I'll be back
